draw_man = {0: ("   ",
                "   ",
                "   "),
            1: (" o ",
                "   ",
                "   "),
            2: (" o ",
                " | ",
                "   "),
            3: (" o ",
                "/| ",
                "   "),
            4: (" o ",
                "/|\\",
                "   "),
            5: (" o ",
                "/|\\",
                "/  "),
            6: (" o ",
                "/|\\",
                "/ \\")}

fruits = ("bananas","strawberries","grapes","apples","watermelon","oranges","blueberries","lemons","peaches","pineapple",
	"potatoes","tomatoes","onions","carrots","broccoli","cucumbers","lettuce","mushrooms","garlic","asparagus")